// Mapa global de ícones da marca Contourline.
// Importar em qualquer tela: `import { IC } from '../src/theme/icons';`
// Uso: <Image source={IC.nuvem} style={...} />

export const IC = {
  // ── Status / Estados ──
  aguardando:        require('../../assets/icons/aguardando.png'),
  enviado:           require('../../assets/icons/enviado.png'),
  enviando:          require('../../assets/icons/enviando.png'),
  erro:              require('../../assets/icons/erro.png'),
  falha:             require('../../assets/icons/falha.png'),
  pausado:           require('../../assets/icons/pausado.png'),
  pendente:          require('../../assets/icons/pendente.png'),
  concluido:         require('../../assets/icons/concluido.png'),
  sincronizado:      require('../../assets/icons/sincronizado.png'),
  sincronizando:     require('../../assets/icons/sincronizando.png'),
  tudoSincronizado:  require('../../assets/icons/tudo_sincronizado.png'),
  check:             require('../../assets/icons/check.png'),
  atencao:           require('../../assets/icons/atencao.png'),

  // ── Conexão / Sinal ──
  semConexao:        require('../../assets/icons/sem_conexao.png'),
  servidorConectado: require('../../assets/icons/servidor_conectado.png'),
  notebookConectado: require('../../assets/icons/notebook_conectado.png'),
  celularConectado:  require('../../assets/icons/celular_conectado.png'),
  sinalForte:        require('../../assets/icons/sinal_forte.png'),
  sinalMedio:        require('../../assets/icons/sinal_medio.png'),
  sinalFraco:        require('../../assets/icons/sinal_fraco.png'),
  wifi:              require('../../assets/icons/wifi.png'),
  bluetooth:         require('../../assets/icons/bluetooth.png'),
  usb:               require('../../assets/icons/usb.png'),

  // ── Navegação (tabs) ──
  navInicio:    require('../../assets/icons/nav_inicio.png'),
  navProjetos:  require('../../assets/icons/nav_projetos.png'),
  navCamera:    require('../../assets/icons/nav_camera.png'),
  navGaleria:   require('../../assets/icons/nav_galeria.png'),
  navUpload:    require('../../assets/icons/nav_upload.png'),

  // ── Câmera ──
  camera:               require('../../assets/icons/camera.png'),
  foto:                 require('../../assets/icons/foto.png'),
  fotoRapida:           require('../../assets/icons/foto_rapida.png'),
  video:                require('../../assets/icons/video.png'),
  livePhoto:            require('../../assets/icons/live_photo.png'),
  flashLigado:          require('../../assets/icons/flash_ligado.png'),
  flashDesativado:      require('../../assets/icons/flash_desativado.png'),
  flashAutomatico:      require('../../assets/icons/flash_automatico.png'),
  focoAutomatico:       require('../../assets/icons/foco_automatico.png'),
  focoTravado:          require('../../assets/icons/foco_travado.png'),
  exposicao:            require('../../assets/icons/exposicao.png'),
  grade:                require('../../assets/icons/grade.png'),
  filtro:               require('../../assets/icons/filtro.png'),
  hdr:                  require('../../assets/icons/hdr.png'),
  raw:                  require('../../assets/icons/raw.png'),
  virarCamera:          require('../../assets/icons/virar_camera.png'),
  gravarSegurar:        require('../../assets/icons/gravar_segurar.png'),
  parar:                require('../../assets/icons/parar.png'),
  pararGravacao:        require('../../assets/icons/parar_gravacao.png'),
  pausar:               require('../../assets/icons/pausar.png'),
  play:                 require('../../assets/icons/play.png'),
  telaCheia:            require('../../assets/icons/tela_cheia.png'),
  timer:                require('../../assets/icons/timer.png'),
  microfoneConectado:   require('../../assets/icons/microfone_conectado.png'),
  microfoneDesconectado:require('../../assets/icons/microfone_desconectado.png'),
  mudo:                 require('../../assets/icons/mudo.png'),
  audioCaptando:        require('../../assets/icons/audio_captando.png'),
  vuMeter:              require('../../assets/icons/vu_meter_video.png'),
  volumeAlto:           require('../../assets/icons/volume_alto.png'),
  volumeMedio:          require('../../assets/icons/volume_medio.png'),
  volumeBaixo:          require('../../assets/icons/volume_baixo.png'),
  engrenagemCamera:     require('../../assets/icons/engrenagem_camera.png'),

  // ── Upload / Nuvem ──
  nuvem:    require('../../assets/icons/nuvem.png'),
  backup:   require('../../assets/icons/backup.png'),
  drive:    require('../../assets/icons/drive.png'),
  download: require('../../assets/icons/download.png'),
  importar: require('../../assets/icons/importar.png'),
  exportar: require('../../assets/icons/exportar.png'),

  // ── Conteúdo / Projetos ──
  eventoPrincipal:  require('../../assets/icons/evento_principal.png'),
  projetoAtivo:     require('../../assets/icons/projeto_ativo.png'),
  treinamento:      require('../../assets/icons/treinamento.png'),
  visita:           require('../../assets/icons/visita.png'),
  demanda:          require('../../assets/icons/demanda.png'),
  conteudoInterno:  require('../../assets/icons/conteudo_interno.png'),
  novoProjeto:      require('../../assets/icons/novo_projeto.png'),
  novoTipo:         require('../../assets/icons/novo_tipo.png'),
  galeria:          require('../../assets/icons/galeria.png'),

  // ── Ações ──
  adicionar:     require('../../assets/icons/adicionar.png'),
  editar:        require('../../assets/icons/editar.png'),
  excluir:       require('../../assets/icons/excluir.png'),
  duplicar:      require('../../assets/icons/duplicar.png'),
  compartilhar:  require('../../assets/icons/compartilhar.png'),
  restaurar:     require('../../assets/icons/restaurar.png'),
  link:          require('../../assets/icons/link.png'),
  buscar:        require('../../assets/icons/buscar.png'),
  ordenar:       require('../../assets/icons/ordenar.png'),
  visualizar:    require('../../assets/icons/visualizar.png'),
  ocultar:       require('../../assets/icons/ocultar.png'),
  fechar:        require('../../assets/icons/fechar.png'),
  travar:        require('../../assets/icons/travar.png'),
  destravar:     require('../../assets/icons/destravar.png'),
  maisOpcoes:    require('../../assets/icons/mais_opcoes.png'),
  menu:          require('../../assets/icons/menu.png'),

  // ── Info ──
  informacoes:    require('../../assets/icons/informacoes.png'),
  ajuda:          require('../../assets/icons/ajuda.png'),
  estatisticas:   require('../../assets/icons/estatisticas.png'),
  relatorio:      require('../../assets/icons/relatorio.png'),
  historico:      require('../../assets/icons/historico.png'),
  atividade:      require('../../assets/icons/atividade.png'),
  notificacoes:   require('../../assets/icons/notificacoes.png'),
  notificacao:    require('../../assets/icons/notificacao.png'),
  perfil:         require('../../assets/icons/perfil.png'),
  favorito:       require('../../assets/icons/favorito.png'),
  calendario:     require('../../assets/icons/calendario.png'),
  localizacao:    require('../../assets/icons/localizacao.png'),
  relogio:        require('../../assets/icons/relogio.png'),
  qrCode:         require('../../assets/icons/qr_code.png'),
  lerQrEvento:    require('../../assets/icons/ler_qr_evento.png'),
  configuracoes:  require('../../assets/icons/engrenagem_configuracoes.png'),

  // ── Chevrons (legados, antes do iconset novo) ──
  chevronDir:   require('../../assets/icons/chevron_direita.png'),
  chevronBaixo: require('../../assets/icons/chevron_baixo.png'),

  // ── Ações Quick (legados do HomeScreen) ──
  acaoCamera:     require('../../assets/icons/acao_camera.png'),
  acaoGaleria:    require('../../assets/icons/acao_galeria.png'),
  acaoQR:         require('../../assets/icons/acao_qr_evento.png'),
  acaoProjeto:    require('../../assets/icons/acao_novo_projeto.png'),
  acaoSeta:       require('../../assets/icons/acao_seta.png'),
};

export default IC;
